export const REPORT_COPY = {
  en: {
    title: 'Tournament Results Report',
    name: 'Name',
    venue: 'Venue',
    date: 'Date',
    nominations: 'Nominations',
    totalFighters: 'Total fighters',
    marshals: 'Marshals',
    noMarshals: 'No marshals were registered.',
    marshal: 'Marshal',
    category: 'Category',
    country: 'Country',
    city: 'City',
    disciplinaryCards: 'Disciplinary cards',
    noDisciplinaryCards: 'No disciplinary cards were issued.',
    cardType: 'Card',
    yellowCard: 'Yellow',
    redCard: 'Red',
    reason: 'Reason',
    nomination: 'Nomination',
    registeredFighters: 'Registered fighters',
    finalResults: 'Final results',
    noFinalResults: 'No final placements were saved.',
    groupStage: 'Group stage',
    olympicStage: 'Olympic stage',
    oneEighthFinal: '1/8 final',
    oneQuarterFinal: '1/4 final',
    semifinals: 'Semifinals',
    final: 'Final',
    round: 'Round',
    bronzeFight: 'Bronze fight',
    group: 'Group',
    results: 'Results',
    fights: 'Fights',
    fight: 'Fight',
    fightNumber: 'Fight #',
    place: 'Place',
    fighter: 'Fighter',
    wins: 'Wins',
    diff: 'Diff',
    fighter1: 'Fighter1',
    vs: '  VS  ',
    blank: '      ',
    fighter2: 'Fighter2',
    score: 'Score',
    winner: 'Winner',
    warning: 'warning',
    fightsCompleted: 'fights completed',
    noData: 'No data',
    notSet: 'Not set',
  },
  ru: {
    title: 'Отчет о результатах турнира',
    name: 'Название',
    venue: 'Место проведения',
    date: 'Дата',
    nominations: 'Номинации',
    totalFighters: 'Всего бойцов',
    marshals: 'Судьи',
    noMarshals: 'Судьи не зарегистрированы.',
    marshal: 'Судья',
    category: 'Категория',
    country: 'Страна',
    city: 'Город',
    disciplinaryCards: 'Дисциплинарные карточки',
    noDisciplinaryCards: 'Дисциплинарные карточки не выдавались.',
    cardType: 'Карточка',
    yellowCard: 'Желтая',
    redCard: 'Красная',
    reason: 'Причина',
    nomination: 'Номинация',
    registeredFighters: 'Зарегистрировано бойцов',
    finalResults: 'Итоговые результаты',
    noFinalResults: 'Итоговые места не сохранены.',
    groupStage: 'Групповой этап',
    olympicStage: 'Олимпийская сетка',
    oneEighthFinal: '1/8 финала',
    oneQuarterFinal: '1/4 финала',
    semifinals: 'Полуфиналы',
    final: 'Финал',
    round: 'Раунд',
    bronzeFight: 'Бой за 3-е место',
    group: 'Группа',
    results: 'Результаты',
    fights: 'Бои',
    fight: 'Бой',
    fightNumber: '№ боя',
    place: 'Место',
    fighter: 'Боец',
    wins: 'Победы',
    diff: 'Разница',
    fighter1: 'Боец 1',
    vs: '  VS  ',
    blank: '      ',
    fighter2: 'Боец 2',
    score: 'Счет',
    winner: 'Победитель',
    warning: 'замечание',
    fightsCompleted: 'боев завершено',
    noData: 'Нет данных',
    notSet: 'Не указано',
  },
} as const;

export type ReportCopy = (typeof REPORT_COPY)[keyof typeof REPORT_COPY];
